CREATE TABLE t_users
(
    Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    email VARCHAR(50),
    password VARCHAR(50),
    fullName VARCHAR(15),
    role VARCHAR(15) DEFAULT 1
);

CREATE TABLE t_items
(
    Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nameItem VARCHAR(15),
    description TEXT,
    price VARCHAR(15) DEFAULT 0,
    picture TEXT
);

CREATE TABLE t_role
(
    Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    role VARCHAR(15)
);